###
# Slurm REST API configuration
###

# Authentication settings
AuthType=auth/munge
AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/etc/slurm/jwt/jwt_hs256.key

# REST API Configuration
DebugFlags=REST_AUTH
RestAuthParameters=jwt_key=/etc/slurm/jwt/jwt_hs256.key
RestServerHost=0.0.0.0
RestServerPort=6820
